apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerdns.fullname" . }}-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ include "metallb.allow-shared-ip" . }}
  labels:
{{ include "powerdns.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{ if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{ end }}
{{- if (.Values.service.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.service.externalTrafficPolicy }}"
{{- end }}
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
  selector:
    app.kubernetes.io/name: {{ include "powerdns.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerdns.fullname" . }}-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ include "metallb.allow-shared-ip" . }}
  labels:
{{ include "powerdns.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{ if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{ end }}
{{- if (.Values.service.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.service.externalTrafficPolicy }}"
{{- end }}
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "powerdns.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ if (.Values.powerdns.api_key) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerdns.fullname" . }}-webserver
  labels:
{{ include "powerdns.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: dns-webserver
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "powerdns.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
